### ISSUE TITLE
Allow to pass the skip parameter to read_d1_data

### ISSUE THREAD

**Issue by brunj7** [NCEAS/metajam#16]
Not top priority, but it will be great to let people to skip potential headers present in the datafile

**Comment by isteves** [comment]
@maier-m proposed to make use of `...` to pass it into the function

**Comment by isteves** [comment]
@brunj7 ...worth checking to see if reading geojson/json files with parameters is possible!  I think the code here should allow it to work

**Comment by brunj7** [comment]
@isteves I tried last night while preparing the talk, but to my surprise could not make it work... will dig more into why.
