### ISSUE TITLE
original filenames not present in the downloaded data file

### ISSUE THREAD

**Issue by brunj7** [NCEAS/metajam#17]
pids examples:

https://cn.dataone.org/cn/v2/resolve/cbfs.21.6
https://cn.dataone.org/cn/v2/resolve/cbfs.149.1
https://cn.dataone.org/cn/v2/resolve/cbfs.151.1

https://pasta.lternet.edu/package/data/eml/knb-lter-and/4021/21/1d31b3fa3d35cefc35cc42f35c3b3a8d
https://portal.lternet.edu/nis/dataviewer?packageid=knb-lter-bnz.152.20&entityid=6fcb1675b162d2c8b2908bcdbe577ec9
https://portal.lternet.edu/nis/dataviewer?packageid=knb-lter-luq.20.4923051&entityid=acb18d969cf36e7efda2604a1449e816
https://portal.lternet.edu/nis/dataviewer?packageid=knb-lter-luq.20.4923051&entityid=6e00fe7811c8fa5ea3919e6ae02775f1

**Comment by isteves** [comment]
@brunj7 this was resolved with #22, correct?
