### ISSUE TITLE
attribute level metadata  csv not created

### ISSUE THREAD

**Issue by brunj7** [NCEAS/metajam#4]
pids used to test:

https://cn.dataone.org/cn/v2/resolve/urn:uuid:ec704da8-f174-49db-b993-bae479cdc5d9
https://cn.dataone.org/cn/v2/resolve/urn:uuid:27074ab8-ff24-4dc3-856d-7e1dc7b717bc
https://cn.dataone.org/cn/v2/resolve/urn:uuid:efb0c44d-e483-434f-bc5c-caa804695760
https://cn.dataone.org/cn/v2/resolve/urn:uuid:0ac36321-d011-4729-bec3-8356aec78cef
https://cn.dataone.org/cn/v2/resolve/urn:uuid:6df440cc-84cd-425b-b9d7-935fc8f11d71

**Comment by maier-m** [comment]
Looking like obsolescence issues here as well.

**Comment by maier-m** [comment]
Tested this and looks to be working fine... closing
