### ISSUE TITLE
summary_metadata.csv

### ISSUE THREAD

**Issue by brunj7** [NCEAS/metajam#6]
Add a header for the first column

Currently:

  | identifier
-- | --
Date_Downloaded | 6/19/18 11:19
Data_ID | urn:uuid:ec704da8-f174-49db-b993-bae479cdc5d9

**Comment by maier-m** [comment]
There should be more if the metadata can be found than what is shown here, but this is a good ticket. Critical to get the right fields here.

**Comment by isteves** [comment]
What header would you like?  In the most recent iteration, I got rid of headers altogether @brunj7

**Comment by brunj7** [comment]
This has been fixed when @isteves updated the function. Closing the issue
