### ISSUE TITLE
unit tests + read_d1_files warning

### ISSUE THREAD

**Issue by dmullen17** [NCEAS/metajam#61]
I've been playing around with `metajam` / reading the source code today.  I noticed only `download_d1_data` has unit tests.  If that's an area of need I can write a few of those.  

I also noticed that `read_d1_files` produces odd error messages if the `fnc` argument is set to `read_csv` for netcdf, excel, and other file types.  I understand not embedding ```eval(parse(text = paste0(fnc, '("', x, '", ...)')))
```  in a `tryCatch` block - because you want it to output error messages if additional arguments are incorrect.  But it might be nice to include a warning message when `read_csv` attempts to read in non-csv files types.

**Comment by brunj7** [comment]
Great you a looking in to `metajam` @dmullen17 ! 

If you have the bandwidth, you are welcomed to add unit tests to `read_d1_files`

Regarding your comment on error handling in this function:

- It seems there is a need to add more documentation on `read_d1_files` and its readr::read_csv default and how to pass extra parameters (e.g. #62)
- We have not fully tested this function on non-tabular format such as json, netcdf, tiff, shapefiles.... this is something we should look into
- More specifically on your suggestion, I think adding a check on the file formats handled by `read_csv` could be useful as it is the default function. This would allow us to help the user to tease out cases when this is the origin of the problem.

**Comment by brunj7** [comment]
Done
