### ISSUE TITLE
Error reading sample data

### ISSUE THREAD

**Issue by gothub** [NCEAS/metajam#62]
The download of data using the example command from the README worked fine, however, an error occurred when trying to read in the data:
```
> download_d1_data("https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3Ac102bac4-a5ea-4699-bfec-8d4ba60948d8", path = ".")
[1] "./doi_10.18739_A2RV0D050__Delta_Junction_Groundwater_2014-2016"
> gw <- read_d1_files("./doi_10.18739_A2RV0D050__Delta_Junction_Groundwater_2014-2016")
Parsed with column specification:
cols(
  attributeName = col_character(),
  attributeDefinition = col_character(),
  formatString = col_character(),
  measurementScale = col_character(),
  unit = col_character(),
  numberType = col_character(),
  missingValueCode = col_integer(),
  missingValueCodeExplanation = col_character(),
  domain = col_character()
)
Parsed with column specification:
cols(
  name = col_character(),
  value = col_character()
)
 Show Traceback
 
 Rerun with Debug
 Error in make.names(x) : invalid multibyte string 1 
```

Not sure but this may be due to the column names of `Delta_Junction_Groundwater_2014-2016.csv` have `(` characters, but the column names aren't enclosed in quotes:
```
> gwd <- read.csv("Delta_Junction_Groundwater_2014-2016.csv")
Error in make.names(col.names, unique = TRUE) : 
  invalid multibyte string 4
```

**Comment by brunj7** [comment]
Same encoding error as in #56  (the degree sign for the Celsius unit) in the original csv

Passing the encoding as parameter to `read_csv `will solve this:

`gw <- read_d1_files("./doi_10.18739_A2RV0D050__Delta_Junction_Groundwater_2014-2016", locale = locale(encoding = "latin1"))`

It seems to be a good user case to add to the documentation.

**Comment by brunj7** [comment]
Created an issue for developing a vignette with examples of passing parameters to `read_d1_files` #67
