### ISSUE TITLE
Error running batch-processing vignette code

### ISSUE THREAD

**Issue by stevenchong** [NCEAS/metajam#64]
I'm running through the batch-processing vignette example and I was able to batch download the datasets.  However, I encountered a warning message when running the following code to read the datasets and their associated metadata into a named list:

` luq_datasets <- map(local_datasets, read_d1_files) %>%  set_names(map(., ~.x$summary_metadata$value[.x$summary_metadata$name == "File_Name"]))`
```
Warning: 29 parsing failures.
row # A tibble: 5 x 5 col     row col   expected          actual file   expected   
<int> <chr> <chr>             <chr>  <chr>    actual 1  1209 DIC   no trailing char… .14

'Data_SEC/https_pasta.lternet.edu_package_metadata_eml_knb-lter-luq… file 2  1210 DIC   no trailing char… .97    
'Data_SEC/https_pasta.lternet.edu_package_metadata_eml_knb-lter-luq… row 3  1211 DIC  no trailing char… .95    
'Data_SEC/https_pasta.lternet.edu_package_metadata_eml_knb-lter-luq… col 4  1212 DIC   no trailing char… .77    
'Data_SEC/https_pasta.lternet.edu_package_metadata_eml_knb-lter-luq… expected' 
```

I suspect this is causing errors further down... For example, when trying to convert the units for the gage height the manual way:

``` 
> RioIcacos_data$Gage_Ht <- 
+   	RioIcacos_data$Gage_Ht * 0.3048
Error in RioIcacos_data$Gage_Ht : 
  $ operator is invalid for atomic vectors
```

**Comment by brunj7** [comment]
Hi @stevenchong 

The parsing error seems to come from the fact that NA are stored as `-9999` but the `DIC` values are float., but since there are no values at the beginning of the dataset, `read_csv` has already set the type to integer, so values are converted to NAs.

So I am not sure it is the problem, but my Rsession does crash at 

```r
RioIcacos_data$Gage_Ht <- ud.convert(RioIcacos_data$Gage_Ht,
                                     RioIcacos_attrmeta$unit[RioIcacos_attrmeta$attributeLabel == "Gage height"], "meter")
```
  looking into why...
