### ISSUE TITLE
vignette function return "no vignettes found"

### ISSUE THREAD

**Issue by brunj7** [NCEAS/metajam#65]
`metajam` vignettes are not listed by the vignette function

```r
library(metajam)

vignette(package="metajam")
# no vignettes found
```

**Comment by gothub** [comment]
It appears that `devtools:build_vignettes()` is creating the rendered vignettes into the `.doc` directory and not `./inst/doc`. When the package is installed then, the `./doc` directory is not included. If I manually move the `./doc` directory to `./inst/doc` and rebuild, the vignettes show up.

I'm not sure how to resolve this problem yet, it may take some perusing of the `build_vignettes` source.

**Comment by brunj7** [comment]
in fact, we need to pass explicitly building vignettes to devtools:

```r
devtools::install_github('NCEAS/metajam', build_vignettes = TRUE)
```
