### ISSUE TITLE
download_d1_data error for specific pid

### ISSUE THREAD

**Issue by brunj7** [NCEAS/metajam#8]
Doing a search for `soil bulk density` on both ADC and KNB, I got those datasets: https://docs.google.com/spreadsheets/d/1QFF5lT4JOPYKZtwykkQ_UDVhHaJSvSGOGsdnkkv3nBE/edit#gid=0

pid `https://cn.dataone.org/cn/v2/resolve/soil2016.5.1`on KNB  is generating the following error 'Error in .x$physical$distribution$online$url$url :    $ operator is invalid for atomic vectors'

**Comment by maier-m** [comment]
The issue has been fixed in https://github.com/NCEAS/metajam/commit/f4c7c5263b5f597facd011ae62cf102883f4c099 .... closing
