### ISSUE TITLE
update dependencies to reflect move of eml2 to eml

### ISSUE THREAD

**Issue by scelmendorf** [NCEAS/metajam#98]
Thanks for making this great package! I'm excited to try it out.
You are probably already aware of this, but eml2 has moved, which means metajam now won't install using the usual devtools::install_github syntax

**Comment by brunj7** [comment]
Hi @scelmendorf ,

Glad you are finding `metajam` useful! We have a pull request open to implement this change. Should be merged soon. I let you know when it is ready.

**Comment by brunj7** [comment]
Hi, 
we have merged the changes that should finalize the implementation of the changes to EML. Please resintall `metajam` at your earliest convenience and let us know if you are experiencing any problems.

Also, we would greatly appreciate if you could give us some more information about the scope of your use of `metajam` (project goal, type of data you are using/analyzing, ...) and how you found this package.

Thank you!

**Comment by scelmendorf** [comment]
Thanks! I will reinstall it and let you know if I have any further issues. For background - We are analyzing a bunch of data from our LTER site (niwot ridge), and I had made a some sample scripts/examples/functions for reproducible workflows reading niwot data/eml directly from EDI . A researcher at our site who was recently at nceas suggested this package might make that even easier, so I thought I'd check it out.
